### ISSUE TITLE
[gcloud-sqlproxy] Adding extraArgs without a value

### ISSUE THREAD

**Issue by bluemalkin** [rimusz/charts#115]
**FEATURE REQUEST**:
Ability to pass extraArgs without a value

**Version of Helm and Kubernetes**:
K8s: 1.20
Helm: 3.7.1

**Which chart**:
gcloud-sqlproxy

**What happened**:
`-enable_iam_login` extraArgs does not have a value: https://github.com/GoogleCloudPlatform/cloudsql-proxy#-enable_iam_login
Thus the chart needs to accomodate extra_args without a value and with a single dash prefix.

**Comment by kipit** [comment]
Others flags are also booleans, for example: `-structured_logs` and `-use_http_health_check`.

The good news is that [Cloud SQL Proxy use](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/e55b0a0aa34f033377934ec78660fe807c77d736/cmd/cloud_sql_proxy/cloud_sql_proxy.go#L52-L133) the standard [Go `flag` package](https://pkg.go.dev/flag) to parse command line options. This package parse boolean flags according these rules:
- [No value, the flag is true](https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/flag/flag.go;l=972)
- [`=1|t|T|true|TRUE|True`, the flag is true](https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/strconv/atob.go;l=12-13)
- [`=0|f|F|false|FALSE|False`, the flag is false](https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/strconv/atob.go;l=14-15)
- [Any other values generates an error](https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/flag/flag.go;l=969;drc=refs%2Ftags%2Fgo1.17.6)

So, because @rimusz uses [the `key=value` form](https://github.com/rimusz/charts/blob/ebae99ba97c1e43991f339c3e63720da16e699c7/stable/gcloud-sqlproxy/templates/deployment.yaml#L71), we are safe and this configuration should make your day:
```yaml
extraArgs:
  enable_iam_login: "true"
```
