### ISSUE TITLE
About the transition from helm/charts to here

### ISSUE THREAD

**Issue by consideRatio** [rimusz/charts#40]
Thank you for the work you have done @rimusz !

I noticed that [helm/charts-gcloud-sqlproxy](https://github.com/helm/charts/tree/master/stable/gcloud-sqlproxy) were initially made available there, but now transitioned here.

What has motivated this move?

**Comment by rimusz** [comment]
hey, yes it was made by me and always was in this repo, also I made it available in `charts/stable`.
As Helm has moved to distributed repo https://hub.helm.sh/ where external hem repos can be added for an easier and quicker PRs acceptance by the maintainers who maintain their charts in their helm repos.

That's why `charts-gcloud-sqlproxy` chart is here and deprecated in `charts/stable`

You are going to see more and more charts moves like this.

If you check (https://hub.helm.sh/charts)[https://hub.helm.sh/charts] you already will many distributed helm repos there

<img width="697" alt="screenshot 2019-01-28 11 33 09" src="https://user-images.githubusercontent.com/5215395/51833882-a22f1200-22f0-11e9-94f3-1de375df3e8a.png">

**Comment by consideRatio** [comment]
Aha! Thank you for taking the time to explain this to me! ;D

**Comment by rimusz** [comment]
no worries
